import type { StockEvent, PricePoint } from "./types";

function makePriceHistory(base: number, days = 30): PricePoint[] {
  const out: PricePoint[] = [];
  let price = base;
  const start = new Date("2026-07-15");
  for (let i = 0; i < days; i++) {
    const d = new Date(start);
    d.setDate(d.getDate() + i);
    price = Math.max(1, price + (Math.random() - 0.48) * base * 0.02);
    out.push({
      date: d.toISOString().slice(0, 10),
      close: Math.round(price),
      volume: Math.round(1_000_000 + Math.random() * 3_000_000),
    });
  }
  return out;
}

export const MOCK_EVENTS: StockEvent[] = [
  {
    id: "evt-2026-08-05-samsung-earnings",
    date: "2026-08-05",
    time: "16:00",
    ticker: "005930",
    companyName: "삼성전자",
    market: "KOSPI",
    type: "earnings",
    title: "삼성전자 2분기 확정실적 발표",
    summary: "잠정치 대비 상향 조정 여부 관전 포인트. HBM3E 매출 반영 규모 주목.",
    isImportant: true,
    detail: {
      articles: [
        {
          id: "a1",
          title: "삼성전자 2분기 확정실적 D-1... 증권가 눈높이는?",
          source: "한국경제",
          publishedAt: "2026-08-04",
          excerpt: "증권가는 삼성전자 2분기 영업이익을 잠정치보다 소폭 상향 조정할 것으로 전망하고 있다.",
        },
        {
          id: "a2",
          title: "HBM3E 12단, 삼성 실적 반등 열쇠",
          source: "매일경제",
          publishedAt: "2026-08-03",
          excerpt: "엔비디아 승인 이후 대량 양산이 본격화되며 하반기 실적 반등의 핵심 축으로 지목된다.",
        },
      ],
      macros: [
        { id: "m1", name: "필라델피아 반도체 지수", value: "5,821", change: "+1.2%" },
        { id: "m2", name: "DXY 달러 인덱스", value: "104.2", change: "-0.3%" },
      ],
      priceHistory: makePriceHistory(78000),
      breakingNews: [],
      flowData: [],
    },
  },
  {
    id: "evt-2026-08-05-fomc-minutes",
    date: "2026-08-05",
    time: "03:00",
    ticker: "-",
    companyName: "美 FOMC",
    market: "-",
    type: "macro",
    title: "FOMC 의사록 공개",
    summary: "7월 회의 의사록. 연내 추가 인하 시그널 여부에 시장 반응 주목.",
    isImportant: true,
    detail: {
      articles: [
        { id: "a1", title: "9월 인하 가능성 70%... 의사록에 힌트 있을까", source: "인베스팅닷컴", publishedAt: "2026-08-04" },
      ],
      macros: [
        { id: "m1", name: "10년물 국채금리", value: "4.12%", change: "-0.03%p" },
        { id: "m2", name: "9월 인하 확률(CME)", value: "72%" },
      ],
      priceHistory: [],
      breakingNews: [],
      flowData: [],
    },
  },
  {
    id: "evt-2026-08-07-sk-hynix-earnings",
    date: "2026-08-07",
    time: "09:00",
    ticker: "000660",
    companyName: "SK하이닉스",
    market: "KOSPI",
    type: "earnings",
    title: "SK하이닉스 2분기 컨퍼런스콜",
    summary: "HBM 매출 비중 및 CapEx 가이던스 업데이트 예정.",
    isImportant: true,
    detail: {
      articles: [
        { id: "a1", title: "SK하이닉스 HBM 매출 비중 60% 돌파 전망", source: "전자신문", publishedAt: "2026-08-06" },
      ],
      macros: [],
      priceHistory: makePriceHistory(215000),
      breakingNews: [],
      flowData: [],
    },
  },
  {
    id: "evt-2026-08-11-cpi",
    date: "2026-08-11",
    time: "21:30",
    ticker: "-",
    companyName: "美 노동통계국",
    market: "-",
    type: "macro",
    title: "미국 7월 CPI 발표",
    summary: "헤드라인·근원 CPI 전년 대비 상승률. 9월 FOMC 결정 방향타.",
    isImportant: true,
    detail: {
      articles: [{ id: "a1", title: "CPI 컨센서스 전년비 2.7% 전망", source: "블룸버그", publishedAt: "2026-08-10" }],
      macros: [
        { id: "m1", name: "직전 CPI(YoY)", value: "3.0%" },
        { id: "m2", name: "근원 CPI(YoY)", value: "3.3%" },
      ],
      priceHistory: [],
      breakingNews: [],
      flowData: [],
    },
  },
  {
    id: "evt-2026-08-12-naver-earnings",
    date: "2026-08-12",
    time: "15:30",
    ticker: "035420",
    companyName: "네이버",
    market: "KOSPI",
    type: "earnings",
    title: "네이버 2분기 실적발표",
    summary: "커머스·핀테크·클라우드 부문별 성장률과 AI 서비스 상용화 진척도 관건.",
    isImportant: true,
    detail: {
      articles: [{ id: "a1", title: "네이버 AI 신사업 매출 첫 공개될까", source: "IT조선", publishedAt: "2026-08-11" }],
      macros: [],
      priceHistory: makePriceHistory(195000),
      breakingNews: [],
      flowData: [],
    },
  },
  {
    id: "evt-2026-08-12-kakao-earnings",
    date: "2026-08-12",
    time: "16:00",
    ticker: "035720",
    companyName: "카카오",
    market: "KOSPI",
    type: "earnings",
    title: "카카오 2분기 실적발표",
    summary: "톡비즈·페이·모빌리티 성장세와 자회사 구조조정 진행률 확인.",
    detail: {
      articles: [],
      macros: [],
      priceHistory: makePriceHistory(43500),
      breakingNews: [],
      flowData: [],
    },
  },
  {
    id: "evt-2026-08-12-lg-electronics",
    date: "2026-08-12",
    time: "10:00",
    ticker: "066570",
    companyName: "LG전자",
    market: "KOSPI",
    type: "earnings",
    title: "LG전자 2분기 컨콜",
    summary: "가전 vs VS(전장) 사업부 마진 격차 및 하반기 가이던스.",
    detail: { articles: [], macros: [], priceHistory: makePriceHistory(102000), breakingNews: [], flowData: [] },
  },
  {
    id: "evt-2026-08-13-hyundai-motor",
    date: "2026-08-13",
    time: "09:30",
    ticker: "005380",
    companyName: "현대차",
    market: "KOSPI",
    type: "earnings",
    title: "현대차 2분기 실적발표",
    summary: "북미 EV 판매·환율 효과 및 하반기 신차 라인업 발표 예정.",
    isImportant: true,
    detail: { articles: [], macros: [], priceHistory: makePriceHistory(238000), breakingNews: [], flowData: [] },
  },
  {
    id: "evt-2026-08-13-kia",
    date: "2026-08-13",
    time: "11:00",
    ticker: "000270",
    companyName: "기아",
    market: "KOSPI",
    type: "earnings",
    title: "기아 2분기 실적발표",
    summary: "PBV(목적기반차량) 사업 진척과 EV3·EV5 판매 성과.",
    detail: { articles: [], macros: [], priceHistory: makePriceHistory(112000), breakingNews: [], flowData: [] },
  },
  {
    id: "evt-2026-08-14-posco",
    date: "2026-08-14",
    time: "14:00",
    ticker: "005490",
    companyName: "POSCO홀딩스",
    market: "KOSPI",
    type: "earnings",
    title: "POSCO홀딩스 2분기 실적발표",
    summary: "리튬·니켈 사업 매출 인식 규모 및 철강 판가 협상 결과.",
    detail: { articles: [], macros: [], priceHistory: makePriceHistory(385000), breakingNews: [], flowData: [] },
  },
  {
    id: "evt-2026-08-14-samsung-dividend",
    date: "2026-08-14",
    ticker: "005930",
    companyName: "삼성전자",
    market: "KOSPI",
    type: "dividend",
    title: "삼성전자 2분기 분기배당 배당락일",
    summary: "주당 361원. 8/14 매수분부터 권리 소멸.",
    detail: { articles: [], macros: [], priceHistory: makePriceHistory(78000, 15), breakingNews: [], flowData: [] },
  },
  {
    id: "evt-2026-08-18-celltrion",
    date: "2026-08-18",
    time: "16:30",
    ticker: "068270",
    companyName: "셀트리온",
    market: "KOSPI",
    type: "earnings",
    title: "셀트리온 2분기 실적발표",
    summary: "짐펜트라 미국 매출 본격 반영 및 바이오시밀러 신제품 승인 이슈.",
    detail: { articles: [], macros: [], priceHistory: makePriceHistory(185000), breakingNews: [], flowData: [] },
  },
  {
    id: "evt-2026-08-19-samsung-bio",
    date: "2026-08-19",
    time: "15:00",
    ticker: "207940",
    companyName: "삼성바이오로직스",
    market: "KOSPI",
    type: "earnings",
    title: "삼성바이오로직스 2분기 실적",
    summary: "5공장 가동률 및 CDO 사업 수주 파이프라인 업데이트.",
    detail: { articles: [], macros: [], priceHistory: makePriceHistory(945000), breakingNews: [], flowData: [] },
  },
  {
    id: "evt-2026-08-20-ipo-nova",
    date: "2026-08-20",
    ticker: "-",
    companyName: "노바메디텍",
    market: "KOSDAQ",
    type: "ipo",
    title: "노바메디텍 코스닥 신규상장",
    summary: "공모가 24,000원. 의료용 AI 진단 솔루션 기업.",
    detail: { articles: [], macros: [], priceHistory: [], breakingNews: [], flowData: [] },
  },
  {
    id: "evt-2026-08-20-ipo-quantum",
    date: "2026-08-20",
    ticker: "-",
    companyName: "퀀텀시스템즈",
    market: "KOSDAQ",
    type: "ipo",
    title: "퀀텀시스템즈 코스닥 상장",
    summary: "공모가 18,500원. 양자통신 하드웨어 개발.",
    detail: { articles: [], macros: [], priceHistory: [], breakingNews: [], flowData: [] },
  },
  {
    id: "evt-2026-08-21-bok",
    date: "2026-08-21",
    time: "10:00",
    ticker: "-",
    companyName: "한국은행 금통위",
    market: "-",
    type: "macro",
    title: "한은 8월 기준금리 결정",
    summary: "현재 3.25%. 8월 동결 vs 25bp 인하 전망 팽팽.",
    isImportant: true,
    detail: {
      articles: [{ id: "a1", title: "금통위 표결 분산 가능성... 소수의견 주목", source: "연합뉴스", publishedAt: "2026-08-20" }],
      macros: [
        { id: "m1", name: "현 기준금리", value: "3.25%" },
        { id: "m2", name: "美 기준금리", value: "5.00%" },
      ],
      priceHistory: [],
      breakingNews: [],
      flowData: [],
    },
  },
  {
    id: "evt-2026-08-22-jackson-hole",
    date: "2026-08-22",
    time: "23:00",
    ticker: "-",
    companyName: "美 연준",
    market: "-",
    type: "macro",
    title: "잭슨홀 심포지엄 파월 연설",
    summary: "9월 인하 시그널 여부. 시장이 가장 주목하는 이벤트.",
    isImportant: true,
    detail: { articles: [], macros: [], priceHistory: [], breakingNews: [], flowData: [] },
  },
  {
    id: "evt-2026-08-25-disclosure-lg-chem",
    date: "2026-08-25",
    ticker: "051910",
    companyName: "LG화학",
    market: "KOSPI",
    type: "disclosure",
    title: "LG화학 자사주 소각 결정 공시",
    summary: "총 3천억원 규모. 주주환원 강화 신호.",
    detail: { articles: [], macros: [], priceHistory: makePriceHistory(345000, 20), breakingNews: [], flowData: [] },
  },
  {
    id: "evt-2026-08-27-nvda",
    date: "2026-08-27",
    time: "05:00",
    ticker: "-",
    companyName: "엔비디아",
    market: "-",
    type: "earnings",
    title: "엔비디아 FY26 2Q 실적발표",
    summary: "데이터센터 매출·Blackwell 램프업 속도. 국내 반도체 섹터 파장 필연.",
    isImportant: true,
    detail: {
      articles: [{ id: "a1", title: "엔비디아 어닝... 국내 시장에 미칠 영향", source: "이데일리", publishedAt: "2026-08-26" }],
      macros: [{ id: "m1", name: "블랙웰 생산 캐파", value: "월 15만대" }],
      priceHistory: [],
      breakingNews: [],
      flowData: [],
    },
  },
  {
    id: "evt-2026-08-28-dividend-kt",
    date: "2026-08-28",
    ticker: "030200",
    companyName: "KT",
    market: "KOSPI",
    type: "dividend",
    title: "KT 반기배당 배당락",
    summary: "주당 500원. 시가배당률 약 1.3%.",
    detail: { articles: [], macros: [], priceHistory: makePriceHistory(38500, 15), breakingNews: [], flowData: [] },
  },
  {
    id: "evt-2026-09-02-ipo-neuro",
    date: "2026-09-02",
    ticker: "-",
    companyName: "뉴로링크바이오",
    market: "KOSDAQ",
    type: "ipo",
    title: "뉴로링크바이오 상장",
    summary: "공모가 32,000원. BCI(뇌-컴퓨터 인터페이스) 국내 첫 상장사.",
    isImportant: true,
    detail: { articles: [], macros: [], priceHistory: [], breakingNews: [], flowData: [] },
  },
  {
    id: "evt-2026-09-05-payroll",
    date: "2026-09-05",
    time: "21:30",
    ticker: "-",
    companyName: "美 노동통계국",
    market: "-",
    type: "macro",
    title: "미국 8월 비농업 고용",
    summary: "9월 FOMC 직전 마지막 고용 데이터. 컨센서스 15만명.",
    isImportant: true,
    detail: { articles: [], macros: [], priceHistory: [], breakingNews: [], flowData: [] },
  },
  {
    id: "evt-2026-09-10-cpi-sept",
    date: "2026-09-10",
    time: "21:30",
    ticker: "-",
    companyName: "美 노동통계국",
    market: "-",
    type: "macro",
    title: "미국 8월 CPI 발표",
    detail: { articles: [], macros: [], priceHistory: [], breakingNews: [], flowData: [] },
    summary: "",
  },
  {
    id: "evt-2026-09-17-fomc",
    date: "2026-09-17",
    time: "03:00",
    ticker: "-",
    companyName: "美 FOMC",
    market: "-",
    type: "macro",
    title: "9월 FOMC 금리 결정",
    summary: "25bp 인하 vs 동결. 점도표 업데이트.",
    isImportant: true,
    detail: {
      articles: [{ id: "a1", title: "9월 FOMC 프리뷰 - 인하 개시 원년", source: "한경", publishedAt: "2026-09-16" }],
      macros: [{ id: "m1", name: "CME 인하 확률", value: "78%" }],
      priceHistory: [],
      breakingNews: [],
      flowData: [],
    },
  },
  {
    id: "evt-2026-09-18-samsung-disc",
    date: "2026-09-18",
    ticker: "005930",
    companyName: "삼성전자",
    market: "KOSPI",
    type: "disclosure",
    title: "삼성전자 임시주총 소집공고",
    summary: "지배구조 개편 안건 상정 예정.",
    detail: { articles: [], macros: [], priceHistory: [], breakingNews: [], flowData: [] },
  },
  {
    id: "evt-2026-09-23-hynix-disc",
    date: "2026-09-23",
    ticker: "000660",
    companyName: "SK하이닉스",
    market: "KOSPI",
    type: "disclosure",
    title: "SK하이닉스 청주 M15X CapEx 공시",
    summary: "HBM 전용 라인 증설 규모 5조원대 예상.",
    detail: { articles: [], macros: [], priceHistory: [], breakingNews: [], flowData: [] },
  },
  {
    id: "evt-2026-09-30-dividend-sk",
    date: "2026-09-30",
    ticker: "034730",
    companyName: "SK",
    market: "KOSPI",
    type: "dividend",
    title: "SK 3분기 분기배당 배당락",
    summary: "주당 1,500원.",
    detail: { articles: [], macros: [], priceHistory: [], breakingNews: [], flowData: [] },
  },
  {
    id: "evt-2026-10-08-bok-oct",
    date: "2026-10-08",
    time: "10:00",
    ticker: "-",
    companyName: "한국은행 금통위",
    market: "-",
    type: "macro",
    title: "한은 10월 기준금리 결정",
    isImportant: true,
    summary: "美 인하 이후 첫 회의. 한미 금리차 축소 가능성.",
    detail: { articles: [], macros: [], priceHistory: [], breakingNews: [], flowData: [] },
  },
  {
    id: "evt-2026-10-10-samsung-pre",
    date: "2026-10-10",
    time: "08:00",
    ticker: "005930",
    companyName: "삼성전자",
    market: "KOSPI",
    type: "earnings",
    title: "삼성전자 3분기 잠정실적",
    isImportant: true,
    summary: "연간 최대 실적 경신 여부. HBM3E 12단 매출 첫 온기 반영 분기.",
    detail: {
      articles: [{ id: "a1", title: "3Q 잠정 D-1... 컨센 15조", source: "머니투데이", publishedAt: "2026-10-09" }],
      macros: [],
      priceHistory: makePriceHistory(82000),
      breakingNews: [],
      flowData: [],
    },
  },
  {
    id: "evt-2026-10-14-cpi-oct",
    date: "2026-10-14",
    time: "21:30",
    ticker: "-",
    companyName: "美 노동통계국",
    market: "-",
    type: "macro",
    title: "미국 9월 CPI 발표",
    summary: "",
    detail: { articles: [], macros: [], priceHistory: [], breakingNews: [], flowData: [] },
  },
  {
    id: "evt-2026-10-15-hynix-pre",
    date: "2026-10-15",
    ticker: "000660",
    companyName: "SK하이닉스",
    market: "KOSPI",
    type: "earnings",
    title: "SK하이닉스 3분기 잠정실적",
    summary: "",
    detail: { articles: [], macros: [], priceHistory: [], breakingNews: [], flowData: [] },
  },
  {
    id: "evt-2026-10-22-lg-energy",
    date: "2026-10-22",
    time: "15:00",
    ticker: "373220",
    companyName: "LG에너지솔루션",
    market: "KOSPI",
    type: "earnings",
    title: "LG에너지솔루션 3분기 실적",
    summary: "IRA 세액공제 규모 및 GM·현대차 합작법인 진척.",
    detail: { articles: [], macros: [], priceHistory: makePriceHistory(410000), breakingNews: [], flowData: [] },
  },
  {
    id: "evt-2026-10-28-fomc-oct",
    date: "2026-10-28",
    time: "03:00",
    ticker: "-",
    companyName: "美 FOMC",
    market: "-",
    type: "macro",
    title: "10월 FOMC 금리 결정",
    isImportant: true,
    summary: "연속 인하 여부 결정.",
    detail: { articles: [], macros: [], priceHistory: [], breakingNews: [], flowData: [] },
  },
  {
    id: "evt-2026-10-30-samsung-conf",
    date: "2026-10-30",
    time: "16:00",
    ticker: "005930",
    companyName: "삼성전자",
    market: "KOSPI",
    type: "earnings",
    title: "삼성전자 3분기 확정실적 컨콜",
    isImportant: true,
    summary: "부문별 실적 및 4분기 가이던스.",
    detail: { articles: [], macros: [], priceHistory: [], breakingNews: [], flowData: [] },
  },
  {
    id: "evt-2026-11-05-payroll-nov",
    date: "2026-11-05",
    time: "21:30",
    ticker: "-",
    companyName: "美 노동통계국",
    market: "-",
    type: "macro",
    title: "미국 10월 비농업 고용",
    summary: "",
    detail: { articles: [], macros: [], priceHistory: [], breakingNews: [], flowData: [] },
  },
  {
    id: "evt-2026-11-12-nvda-q3",
    date: "2026-11-12",
    time: "05:00",
    ticker: "-",
    companyName: "엔비디아",
    market: "-",
    type: "earnings",
    title: "엔비디아 FY26 3Q 실적",
    isImportant: true,
    summary: "블랙웰 첫 온기 반영 실적.",
    detail: { articles: [], macros: [], priceHistory: [], breakingNews: [], flowData: [] },
  },
  {
    id: "evt-2026-11-13-cpi-nov",
    date: "2026-11-13",
    time: "21:30",
    ticker: "-",
    companyName: "美 노동통계국",
    market: "-",
    type: "macro",
    title: "미국 10월 CPI 발표",
    summary: "",
    detail: { articles: [], macros: [], priceHistory: [], breakingNews: [], flowData: [] },
  },
  {
    id: "evt-2026-11-27-bok-nov",
    date: "2026-11-27",
    time: "10:00",
    ticker: "-",
    companyName: "한국은행 금통위",
    market: "-",
    type: "macro",
    title: "한은 11월 기준금리 결정",
    summary: "올해 마지막 금통위. 수정경제전망 함께 발표.",
    isImportant: true,
    detail: { articles: [], macros: [], priceHistory: [], breakingNews: [], flowData: [] },
  },
];
